package:
   name: intake-mongo
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - python
    - intake>=0.2
    - pymongo

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - py.test --verbose --cov=intake_mongo tests

about:
  home: https://github.com/ContinuumIO/intake-mongo
  license: BSD
  license_file: LICENSE
  summary: |
    MongoDB plugin for Intake
